// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebAPI.OpenFinance.Data;

#nullable disable

namespace WebAPI.OpenFinance.Migrations
{
    [DbContext(typeof(OpenFinanceContext))]
    partial class OpenFinanceContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebAPI.OpenFinance.Models.BanksModel", b =>
                {
                    b.Property<int>("bankID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("bank_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("bankID"));

                    b.Property<string>("bankName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("bank_name");

                    b.HasKey("bankID");

                    b.ToTable("banks");
                });

            modelBuilder.Entity("WebAPI.OpenFinance.Models.ClientsModel", b =>
                {
                    b.Property<int>("clientID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("client_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("clientID"));

                    b.Property<string>("clientAddress")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("client_address");

                    b.Property<string>("clientEmail")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("client_email");

                    b.Property<string>("clientName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("client_name");

                    b.HasKey("clientID");

                    b.ToTable("clients");
                });

            modelBuilder.Entity("WebAPI.OpenFinance.Models.ConnectionsModel", b =>
                {
                    b.Property<int>("connectionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("connection_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("connectionID"));

                    b.Property<int>("accountNumber")
                        .HasColumnType("integer")
                        .HasColumnName("account_number");

                    b.Property<int>("bankID")
                        .HasColumnType("integer")
                        .HasColumnName("bank_id");

                    b.Property<int>("clientID")
                        .HasColumnType("integer")
                        .HasColumnName("client_id");

                    b.HasKey("connectionID");

                    b.ToTable("connections");
                });
#pragma warning restore 612, 618
        }
    }
}
